// Code generated by mockery v2.53.5. DO NOT EDIT.

package validator

import (
	models "anomaly_detector/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIRequestValidator is an autogenerated mock type for the IRequestValidator type
type MockIRequestValidator struct {
	mock.Mock
}

type MockIRequestValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRequestValidator) EXPECT() *MockIRequestValidator_Expecter {
	return &MockIRequestValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx, req, model
func (_m *MockIRequestValidator) Validate(ctx context.Context, req *models.Request, model *models.APIModel) []*models.FieldAnomaly {
	ret := _m.Called(ctx, req, model)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 []*models.FieldAnomaly
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request, *models.APIModel) []*models.FieldAnomaly); ok {
		r0 = rf(ctx, req, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FieldAnomaly)
		}
	}

	return r0
}

// MockIRequestValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockIRequestValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
//   - model *models.APIModel
func (_e *MockIRequestValidator_Expecter) Validate(ctx interface{}, req interface{}, model interface{}) *MockIRequestValidator_Validate_Call {
	return &MockIRequestValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, req, model)}
}

func (_c *MockIRequestValidator_Validate_Call) Run(run func(ctx context.Context, req *models.Request, model *models.APIModel)) *MockIRequestValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request), args[2].(*models.APIModel))
	})
	return _c
}

func (_c *MockIRequestValidator_Validate_Call) Return(_a0 []*models.FieldAnomaly) *MockIRequestValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestValidator_Validate_Call) RunAndReturn(run func(context.Context, *models.Request, *models.APIModel) []*models.FieldAnomaly) *MockIRequestValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRequestValidator creates a new instance of MockIRequestValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRequestValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRequestValidator {
	mock := &MockIRequestValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
