// Code generated by mockery v2.53.5. DO NOT EDIT.

package store

import (
	models "anomaly_detector/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIModelStore is an autogenerated mock type for the IModelStore type
type MockIModelStore struct {
	mock.Mock
}

type MockIModelStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIModelStore) EXPECT() *MockIModelStore_Expecter {
	return &MockIModelStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, path, method
func (_m *MockIModelStore) Get(ctx context.Context, path string, method string) (*models.APIModel, error) {
	ret := _m.Called(ctx, path, method)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.APIModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.APIModel, error)); ok {
		return rf(ctx, path, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.APIModel); ok {
		r0 = rf(ctx, path, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIModelStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIModelStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - method string
func (_e *MockIModelStore_Expecter) Get(ctx interface{}, path interface{}, method interface{}) *MockIModelStore_Get_Call {
	return &MockIModelStore_Get_Call{Call: _e.mock.On("Get", ctx, path, method)}
}

func (_c *MockIModelStore_Get_Call) Run(run func(ctx context.Context, path string, method string)) *MockIModelStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIModelStore_Get_Call) Return(_a0 *models.APIModel, _a1 error) *MockIModelStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIModelStore_Get_Call) RunAndReturn(run func(context.Context, string, string) (*models.APIModel, error)) *MockIModelStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, model
func (_m *MockIModelStore) Store(ctx context.Context, model *models.APIModel) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.APIModel) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIModelStore_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockIModelStore_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.APIModel
func (_e *MockIModelStore_Expecter) Store(ctx interface{}, model interface{}) *MockIModelStore_Store_Call {
	return &MockIModelStore_Store_Call{Call: _e.mock.On("Store", ctx, model)}
}

func (_c *MockIModelStore_Store_Call) Run(run func(ctx context.Context, model *models.APIModel)) *MockIModelStore_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.APIModel))
	})
	return _c
}

func (_c *MockIModelStore_Store_Call) Return(_a0 error) *MockIModelStore_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIModelStore_Store_Call) RunAndReturn(run func(context.Context, *models.APIModel) error) *MockIModelStore_Store_Call {
	_c.Call.Return(run)
	return _c
}

// StoreAll provides a mock function with given fields: ctx, _a1
func (_m *MockIModelStore) StoreAll(ctx context.Context, _a1 []*models.APIModel) (int, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for StoreAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.APIModel) (int, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.APIModel) int); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.APIModel) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIModelStore_StoreAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreAll'
type MockIModelStore_StoreAll_Call struct {
	*mock.Call
}

// StoreAll is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 []*models.APIModel
func (_e *MockIModelStore_Expecter) StoreAll(ctx interface{}, _a1 interface{}) *MockIModelStore_StoreAll_Call {
	return &MockIModelStore_StoreAll_Call{Call: _e.mock.On("StoreAll", ctx, _a1)}
}

func (_c *MockIModelStore_StoreAll_Call) Run(run func(ctx context.Context, _a1 []*models.APIModel)) *MockIModelStore_StoreAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.APIModel))
	})
	return _c
}

func (_c *MockIModelStore_StoreAll_Call) Return(_a0 int, _a1 error) *MockIModelStore_StoreAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIModelStore_StoreAll_Call) RunAndReturn(run func(context.Context, []*models.APIModel) (int, error)) *MockIModelStore_StoreAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIModelStore creates a new instance of MockIModelStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIModelStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIModelStore {
	mock := &MockIModelStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
